# Generated by Django 2.2.2 on 2019-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('deliveryEstimate', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagePath', models.ImageField(null=True, upload_to='fotos_restaurantes')),
                ('about', models.CharField(max_length=150)),
                ('hours', models.CharField(max_length=150)),
            ],
        ),
    ]
