# Generated by Django 2.2.2 on 2019-06-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('optionalAddress', models.CharField(max_length=500, null=True)),
                ('number', models.IntegerField()),
                ('paymentOption', models.CharField(max_length=500)),
                ('orderItems', models.CharField(max_length=1000)),
            ],
        ),
    ]
