# Generated by Django 2.2.2 on 2019-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderItems',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentOption',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
