# Generated by Django 2.2.2 on 2019-06-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190623_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='emailConfirmation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
