# Generated by Django 2.2.2 on 2019-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0003_remove_orderitems_order'),
        ('orders', '0006_remove_orders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderItems',
            field=models.ManyToManyField(to='orderitems.OrderItems'),
        ),
    ]
