# Generated by Django 2.2.2 on 2019-06-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_remove_orders_orderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('orderItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_id', to='orders.Orders')),
            ],
        ),
    ]
