# Generated by Django 2.2.2 on 2019-06-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='orderItems',
            new_name='order',
        ),
    ]
