# Generated by Django 2.2.2 on 2019-06-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_auto_20190624_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
    ]
