# Generated by Django 2.2.2 on 2019-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.CharField(max_length=150)),
            ],
        ),
    ]
