# Generated by Django 2.2.2 on 2019-06-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='restaurantId',
            field=models.IntegerField(null=True),
        ),
    ]
