# Generated by Django 2.2.2 on 2019-06-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
