# Generated by Django 2.2.2 on 2019-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.ImageField(null=True, upload_to='fotos_menu')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurantId', models.IntegerField(null=True)),
            ],
        ),
    ]
